### ISSUE TITLE
Switch the sphinx theme

### ISSUE THREAD

**Issue by goodboy** [goodboy/tractor#132]
I've got a more *black and white* theme idea in my head (to match with the new logo :exploding_head:) so I was thinking let's try out some other theme options:
- [Typlog](https://sphinxthemes.com/themes/typlog) looks very close to what I was thinking
- [Awesome](https://sphinxthemes.com/themes/awesome) isn't bad either

I think using `Typlog` in particular might result in the sections feeling a little less like part of a long read.
It's worth trying out at the least.

**Comment by goodboy** [comment]
```python
Running Sphinx v1.8.5
loading translations [en]... done
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tractor/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tractor/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 263, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tractor/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 324, in _init_builder
    self.builder.init()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tractor/envs/latest/lib/python3.7/site-packages/sphinx/builders/html.py", line 329, in init
    self.init_templates()
  File "/home/docs/checkouts/readthedocs.org/user_builds/tractor/envs/latest/lib/python3.7/site-packages/sphinx/builders/html.py", line 375, in init_templates
    self.theme = theme_factory.create(themename)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tractor/envs/latest/lib/python3.7/site-packages/sphinx/theming.py", line 286, in create
    '(missing theme.conf?)') % name)
sphinx.errors.ThemeError: no theme named 'sphinx_typlog_theme' found (missing theme.conf?)

Theme error:
no theme named 'sphinx_typlog_theme' found (missing theme.conf?)
```

@guilledk from RTD :cry:
